# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4508b9e6aa6b7ff09705feded5cf02dd3957117c9f76f2bb1ad0c57df11843278c5b7b14bcf0f5c63ea7aa71a7ce36c0becc8454f077453448a1a53be84c9cbb

test:
  secret_key_base: bbb50a3bfa708ed62a53d31eb9dfcd122c7c1e1e084a00e26d184c26f38e6fb6edb330b5c3b387f0129f1888a6620c9637d8f04ee5b42c7fb939d9a1b2ac278f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
